remote_theme: pages-themes/primer@v0.6.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: mmistakes/minimal-mistakes@v4.27.3
# theme: jekyll-theme-minimal-mistakes

plugins:
- jekyll-remote-theme
- jekyll-toc
- jekyll-mermaid
- jekyll-numbered-headings

# use_math: true
toc: true
mermaid: true
full-width: true

markdown: kramdown
# mathjax: true
kramdown:
  # math_engine: mathjax
  math_engine: null
  input: GFM
  auto_ids: true
  syntax_highlighter_opts:
    disable: true
  heaeder_numbering: true
